name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cibw_arch: ['all']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install -U cibuildwheel==2.16.5

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: 'cp38-* cp39-* cp310-* cp311-*'
          CIBW_SKIP: '*-musllinux_*'
          CIBW_ARCHS: ${{ matrix.cibw_arch }}

      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
          # repository_url: https://test.pypi.org/legacy/
